package com.univali.listamunicipios;

import java.util.ArrayList;
import java.util.List;

public class Santa_Catarina {

    private final List<Cidade> cidades;

    public Santa_Catarina() {
        cidades = new ArrayList<Cidade>();
        cidades.add(new Cidade("Abdon Batista"                   ,2656        ,235.600      ,11.27));
        cidades.add(new Cidade("Agrolândia"                      ,9957        ,207.119      ,48.07));
        cidades.add(new Cidade("AbelardoLuz"                     ,17584       ,1055.368     ,16.66));
        cidades.add(new Cidade("Água Doce"                       ,7110        ,1311.000     ,5.42));
        cidades.add(new Cidade("Agronômica"                      ,5172        ,135.923      ,38.05));
        cidades.add(new Cidade("Águas Mornas"                    ,5926        ,360.757      ,16.42));
        cidades.add(new Cidade("Águas Frias"                     ,2430        ,75.162       ,32.33));
        cidades.add(new Cidade("Alfredo Wagner"                  ,9737        ,732.277      ,13.29));
        cidades.add(new Cidade("Águas de Chapecó"                ,313         ,139.132      ,45.37));
        cidades.add(new Cidade("Anchieta"                        ,6145        ,228.580      ,26.88));
        cidades.add(new Cidade("Alto Bela Vista"                 ,2007        ,103.592      ,19.37));
        cidades.add(new Cidade("Anita Garibaldi"                 ,8230        ,588.612      ,13.98));
        cidades.add(new Cidade("Angelina"                        ,5166        ,499.947      ,10.33));
        cidades.add(new Cidade("Antônio Carlos"                  ,7906        ,229.118      ,34.5));
        cidades.add(new Cidade("Anitápolis"                      ,3259        ,542.380      ,6.00));
        cidades.add(new Cidade("Arabutã"                         ,4270        ,132.232      ,32.29));
        cidades.add(new Cidade("Apiúna"                          ,10099       ,493.529      ,20.46));
        cidades.add(new Cidade("Araranguá"                       ,68228       ,303.799      ,211.99));
        cidades.add(new Cidade("Araquari"                        ,29593       ,401.831      ,73.54));
        cidades.add(new Cidade("Arroio Trinta"                   ,3562        ,94.333       ,37.75));
        cidades.add(new Cidade("Armazém"                         ,8159        ,173.484      ,47.03));
        cidades.add(new Cidade("Ascurra"                         ,7683        ,111.672      ,68.79));
        cidades.add(new Cidade("Arvoredo"                        ,2240        ,90.709       ,25.14));
        cidades.add(new Cidade("Aurora"                          ,5661        ,206.947      ,27.35));
        cidades.add(new Cidade("Atalanta"                        ,3310        ,94.527       ,35.01));
        cidades.add(new Cidade("Balneário Barra do Sul"          ,9330        ,110.428      ,84.48));
        cidades.add(new Cidade("Balneário Arroio do Silva"       ,10876       ,93.819       ,115.92));
        cidades.add(new Cidade("Balneário Gaivota"               ,9259        ,147.710      ,62.68));
        cidades.add(new Cidade("Balneário Camboriú"              ,142295      ,46.489       ,2601.17));
        cidades.add(new Cidade("Balneário Rincão"                ,11628       ,57.88        ,200.89    ));
        cidades.add(new Cidade("Balneário Piçarras"              ,19329       ,99.071       ,195.10));
        cidades.add(new Cidade("Barra Bonita"                    ,1842        ,93.469       ,19.70));
        cidades.add(new Cidade("Bandeirante"                     ,2865        ,146.255      ,19.58));
        cidades.add(new Cidade("Bela Vista do Toldo"             ,6191        ,534.618      ,11.58));
        cidades.add(new Cidade("Barra Velha"                     ,24943       ,140.160      ,177.96));
        cidades.add(new Cidade("Benedito Novo"                   ,10906       ,385.402      ,28.29));
        cidades.add(new Cidade("Belmonte"                        ,2692        ,93.604       ,28.75));
        cidades.add(new Cidade("Blumenau"                        ,357199      ,519.8        ,633.09));
        cidades.add(new Cidade("Biguaçu"                         ,68481       ,324.521      ,192.23));
        cidades.add(new Cidade("Bom Jardim da Serra"             ,4566        ,935.177      ,4.88));
        cidades.add(new Cidade("Bocaina do Sul"                  ,3393        ,496.250      ,6.83));
        cidades.add(new Cidade("Bom Jesus do Oeste"              ,2160        ,67.899       ,31.81));
        cidades.add(new Cidade("Bom Jesus"                       ,3010        ,63.522       ,42.85));
        cidades.add(new Cidade("Bombinhas"                       ,16311       ,34.489       ,472.93));
        cidades.add(new Cidade("Bom Retiro"                      ,9397        ,1055.501     ,8.90));
        cidades.add(new Cidade("Braço do Norte"                  ,30868       ,223.91       ,137.85));
        cidades.add(new Cidade("Botuverá"                        ,4785        ,303.023      ,15.79));
        cidades.add(new Cidade("Brunópolis"                      ,2741        ,335.513      ,8.16));
        cidades.add(new Cidade("Braço do Trombudo"               ,3599        ,89.681       ,40.13));
        cidades.add(new Cidade("Caçador"                         ,78595       ,981.901      ,73.60));
        cidades.add(new Cidade("Brusque"                         ,134723      ,280.66       ,415.57));
        cidades.add(new Cidade("Calmon"                          ,3380        ,639.528      ,5.29));
        cidades.add(new Cidade("Caibi"                           ,6274        ,171.711      ,36.53));
        cidades.add(new Cidade("Campo Alegre"                    ,11982       ,496.146      ,24.15));
        cidades.add(new Cidade("Camboriú"                        ,82989       ,212320.0     ,293.62));
        cidades.add(new Cidade("Campo Erê"                       ,9370        ,478.734      ,19.57));
        cidades.add(new Cidade("Campo Belo do Sul"               ,7486        ,1027.650     ,7.29));
        cidades.add(new Cidade("Canelinha"                       ,11781       ,151.409      ,77.81));
        cidades.add(new Cidade("Campos Novos"                    ,35710       ,1719.373     ,21.52));
        cidades.add(new Cidade("Capinzal"                        ,22524       ,333.980      ,67.44));
        cidades.add(new Cidade("Canoinhas"                       ,52765       ,1144.84      ,46.09));
        cidades.add(new Cidade("Capão Alto"                      ,2753        ,1335.832     ,2.06));
        cidades.add(new Cidade("Capivari de Baixo"               ,21689       ,53.165       ,407.96));
        cidades.add(new Cidade("Caxambu do Sul"                  ,902         ,140.600     ,31.34));
        cidades.add(new Cidade("Catanduvas"                      ,9558        ,198.033      ,48.26));
        cidades.add(new Cidade("Cerro Negro"                     ,3417        ,416.774      ,8.2));
        cidades.add(new Cidade("Celso Ramos"                     ,2768        ,189.970      ,null));
        cidades.add(new Cidade("Chapecó"                         ,220367      ,626.060      ,316.56));
        cidades.add(new Cidade("Chapadão do Lageado"             ,2892        ,124.472      ,null));
        cidades.add(new Cidade("Concórdia"                       ,74641       ,797.260      ,86.32));
        cidades.add(new Cidade("Cocal do Sul"                    ,15269       ,78.547       ,null));
        cidades.add(new Cidade("Coronel Freitas"                 ,null      ,null,null));
        cidades.add(new Cidade("Cordilheira Alta"                ,null        ,null  ,null));
        cidades.add(new Cidade("Correia Pinto"                   ,14794       ,651.614      ,22.7));
        cidades.add(new Cidade("Coronel Martins"                 ,null      ,null,null));
        cidades.add(new Cidade("Criciúma"                        ,215186      ,235.628      ,904.06));
        cidades.add(new Cidade("Corupá"                          ,15337       ,405.003      ,37.87));
        cidades.add(new Cidade("Cunhataí"                        ,1882        ,54.511       ,34.53));
        cidades.add(new Cidade("Cunha Porã"                      ,10982       ,220.293      ,49.85));
        cidades.add(new Cidade("Descanso"                        ,8638        ,285.571      ,30.25));
        cidades.add(new Cidade("Curitibanos"                     ,38799       ,952.283      ,39.67));
        cidades.add(new Cidade("Dona Emma"                       ,3723        ,181.018      ,20.57));
        cidades.add(new Cidade("Dionísio Cerqueira"              ,15450       ,377.704      ,40.91));
        cidades.add(new Cidade("Entre Rios"                      ,3018        ,105.167      ,28.7));
        cidades.add(new Cidade("Doutor Pedrinho"                 ,3990        ,375.758      ,10.62));
        cidades.add(new Cidade("Erval Velho"                     ,4353        ,207.686      ,20.96));
        cidades.add(new Cidade("Ermo"                            ,2050        ,63.868       ,32.1));
        cidades.add(new Cidade("Flor do Sertão"                  ,1588        ,58.708       ,27.05));
        cidades.add(new Cidade("Faxinal dos Guedes"              ,10686       ,339.966      ,31.46));
        cidades.add(new Cidade("Formosa do Sul"                  ,2601        ,99.576       ,26.12));
        cidades.add(new Cidade("Florianópolis"                   ,500973      ,675.409      ,671.12));
        cidades.add(new Cidade("Fraiburgo"                       ,36443       ,546.249      ,0.07));
        cidades.add(new Cidade("Forquilhinha"                    ,25988       ,183.134      ,0.14));
        cidades.add(new Cidade("Galvão"                          ,3475        ,121.900      ,28.51));
        cidades.add(new Cidade("Frei Rogério"                    ,2480        ,157.845      ,15.71));
        cidades.add(new Cidade("Garuva"                          ,16081       ,503.000      ,0.03));
        cidades.add(new Cidade("Garopaba"                        ,18144       ,114.670      ,158.23));
        cidades.add(new Cidade("Governador Celso Ramos"          ,13655       ,117.182      ,116.53));
        cidades.add(new Cidade("Gaspar"                          ,69639       ,386.776      ,171.19));
        cidades.add(new Cidade("Gravatal"                        ,10636       ,168.500      ,null));
        cidades.add(new Cidade("Grão Pará"                       ,6278        ,328.097      ,19.1));
        cidades.add(new Cidade("Guaraciaba"                      ,10604       ,330.600      ,null));
        cidades.add(new Cidade("Guabiruba"                       ,21800       ,173.600      ,null));
        cidades.add(new Cidade("Guarujá do Sul"                  ,null        ,null             ,null        ));
        cidades.add(new Cidade("Guaramirim"                      ,44873       ,268.119      ,167.36));
        cidades.add(new Cidade("Herval d Oeste"                  ,21233       ,222.405      ,95.47));
        cidades.add(new Cidade("Guatambu"                        ,null        ,null             ,null        ));
        cidades.add(new Cidade("Ibicaré"                         ,3373        ,150.500      ,null));
        cidades.add(new Cidade("Ibiam"                           ,1971        ,null ,null));
        cidades.add(new Cidade("Içara"                           ,52284       ,228.928      ,228.39));
        cidades.add(new Cidade("Ibirama"                         ,17342       ,246.705      ,70.29));
        cidades.add(new Cidade("Imaruí"                          ,11672       ,542.236      ,21.53));
        cidades.add(new Cidade("Ilhota"                          ,13857       ,253.442      ,54.68));
        cidades.add(new Cidade("Imbuia"                          ,null        ,null     ,null));
        cidades.add(new Cidade("Imbituba"                        ,44412       ,184.787      ,240.34));
        cidades.add(new Cidade("Iomerê"                          ,null        ,null     ,null));
        cidades.add(new Cidade("Indaial"                         ,69425       ,430.534      ,154.45));
        cidades.add(new Cidade("Iporã do Oeste"                  ,null      ,null,null));
        cidades.add(new Cidade("Ipira"                           ,null        ,null,null));
        cidades.add(new Cidade("Ipumirim"                        ,null        ,null,null));
        cidades.add(new Cidade("Ipuaçu"                          ,null   ,null,null));
        cidades.add(new Cidade("Irani"                           ,9534        ,321.559      ,29.65));
        cidades.add(new Cidade("Iraceminha"                      ,null  ,null,null));
        cidades.add(new Cidade("Irineópolis"                     ,null  ,null,null));
        cidades.add(new Cidade("Irati"                           ,null  ,null,null));
        cidades.add(new Cidade("Itaiópolis"                      ,20315       ,1295.431     ,15.68));
        cidades.add(new Cidade("Itá"                             ,6427        ,165.463      ,38.84));
        cidades.add(new Cidade("Itapema"                         ,65312       ,59.022       ,1036.68));
        cidades.add(new Cidade("Itajaí"                          ,219536      ,289.255      ,735.04));
        cidades.add(new Cidade("Itapoá"                          ,14763       ,256.1        ,57.45));
        cidades.add(new Cidade("Itapiranga"                      ,16736       ,280.116      ,59.75));
        cidades.add(new Cidade("Jaborá"                          ,null  ,null,null));
        cidades.add(new Cidade("Ituporanga"                      ,24061       ,336.955      ,71.41));
        cidades.add(new Cidade("Jaguaruna"                       ,16418       ,329.459      ,48.7));
        cidades.add(new Cidade("Jacinto Machado"                 ,null      ,null,null));
        cidades.add(new Cidade("Jardinópolis"                    ,null      ,null,null));
        cidades.add(new Cidade("Jaraguá do Sul"                  ,177697      ,532.590      ,278.55));
        cidades.add(new Cidade("Joinville"                       ,590466      ,1126.106     ,465.42));
        cidades.add(new Cidade("Joaçaba"                         ,30118       ,232.354      ,127.43));
        cidades.add(new Cidade("Jupiá"                           ,null        ,null  ,null));
        cidades.add(new Cidade("José Boiteux"                    ,5054        ,405.519      ,11.5));
        cidades.add(new Cidade("Lages"                           ,157544      ,2631.504     ,59.65));
        cidades.add(new Cidade("Lacerdópolis"                    ,null      ,null,null));
        cidades.add(new Cidade("Lajeado Grande"                  ,null      ,null,null));
        cidades.add(new Cidade("Laguna"                          ,44982       ,336.396      ,133.72));
        cidades.add(new Cidade("Lauro Müller"                    ,14426       ,270.508      ,53.33));
        cidades.add(new Cidade("Laurentino"                      ,null  ,null,null));
        cidades.add(new Cidade("Leoberto Leal"                   ,3365        ,291.191      ,11.56));
        cidades.add(new Cidade("Lebon Régis"                     ,null  ,null,null));
        cidades.add(new Cidade("Lontras"                         ,10248       ,198.397      ,51.65));
        cidades.add(new Cidade("Lindóia do Sul"                  ,null      ,null,null));
        cidades.add(new Cidade("Luzerna"                         ,5599        ,116.832      ,27.92));
        cidades.add(new Cidade("Luiz Alves"                      ,12162       ,260.079      ,46.76));
        cidades.add(new Cidade("Mafra"                           ,56017       ,1404.034     ,39.9));
        cidades.add(new Cidade("Macieira"                        ,null  ,null,null));
        cidades.add(new Cidade("Major Vieira"                    ,null      ,null,null));
        cidades.add(new Cidade("Major Gercino"                   ,null      ,null,null));
        cidades.add(new Cidade("Maravilha"                       ,25762       ,null ,null));
        cidades.add(new Cidade("Maracajá"                        ,null  ,null,null));
        cidades.add(new Cidade("Massaranduba"                    ,null      ,null,null));
        cidades.add(new Cidade("Marema"                          ,null  ,null,null));
        cidades.add(new Cidade("Meleiro"                         ,null  ,null,null));
        cidades.add(new Cidade("Matos Costa"                     ,2839        ,433.073      ,6.56));
        cidades.add(new Cidade("Modelo"                          ,null  ,null,null));
        cidades.add(new Cidade("Mirim Doce"                      ,null  ,null,null));
        cidades.add(new Cidade("Monte Carlo"                     ,10874       ,162.800      ,null));
        cidades.add(new Cidade("Mondaí"                          ,null  ,null,null));
        cidades.add(new Cidade("Morro da Fumaça"                 ,null      ,null,null));
        cidades.add(new Cidade("Monte Castelo"                   ,null      ,null,null));
        cidades.add(new Cidade("Navegantes"                      ,81475       ,111.461      ,633.09));
        cidades.add(new Cidade("Morro Grande"                    ,null      ,null,null));
        cidades.add(new Cidade("Nova Itaberaba"                  ,null      ,null,null));
        cidades.add(new Cidade("Nova Erechim"                    ,null      ,null,null));
        cidades.add(new Cidade("Nova Veneza"                     ,null  ,null,null));
        cidades.add(new Cidade("Nova Trento"                     ,12179       ,402.118      ,30.29));
        cidades.add(new Cidade("Orleans"                         ,22311       ,549.824      ,40.58));
        cidades.add(new Cidade("Novo Horizonte"                  ,null      ,null,null));
        cidades.add(new Cidade("Ouro"                            ,null  ,null,null));
        cidades.add(new Cidade("Otacílio Costa"                  ,null      ,null,null));
        cidades.add(new Cidade("Paial"                           ,null  ,null,null));
        cidades.add(new Cidade("Ouro Verde"                      ,null  ,null,null));
        cidades.add(new Cidade("Palhoça"                         ,171797      ,395.133      ,425.83));
        cidades.add(new Cidade("Painel"                          ,null  ,null,null));
        cidades.add(new Cidade("Palmeira"                        ,null  ,null,null));
        cidades.add(new Cidade("Palma Sola"                      ,null  ,null,null));
        cidades.add(new Cidade("Papanduva"                       ,null  ,null,null));
        cidades.add(new Cidade("Palmitos"                        ,null  ,null,null));
        cidades.add(new Cidade("Passo de Torres"                 ,8142        ,95.114       ,85.6));
        cidades.add(new Cidade("Paraíso"                         ,4080        ,181.243      ,22.5));
        cidades.add(new Cidade("Paulo Lopes"                     ,6692        ,450.372      ,14.86));
        cidades.add(new Cidade("Passos Maia"                     ,null  ,null,null));
        cidades.add(new Cidade("Penha"                           ,31764       ,58.783       ,540.36));
        cidades.add(new Cidade("Pedras Grandes"                  ,4107        ,171.821      ,23.9));
        cidades.add(new Cidade("Pescaria Brava"                  ,9761        ,120.60       ,80.9     ));
        cidades.add(new Cidade("Peritiba"                        ,null  ,null,null));
        cidades.add(new Cidade("Pinhalzinho"                     ,20313       ,null ,null));
        cidades.add(new Cidade("Petrolândia"                     ,6131        ,306.153      ,20.3));
        cidades.add(new Cidade("Piratuba"                        ,4102        ,145.976      ,28.1));
        cidades.add(new Cidade("Pinheiro Preto"                  ,null      ,null,null));
        cidades.add(new Cidade("Pomerode"                        ,32334       ,214.727      ,150.58));
        cidades.add(new Cidade("Planalto Alegre"                 ,2659        ,62.632       ,42.45));
        cidades.add(new Cidade("Ponte Alta"                      ,null  ,null,null));
        cidades.add(new Cidade("Ponte Alta do Norte"             ,null        ,null  ,null));
        cidades.add(new Cidade("Porto Belo"                      ,16118       ,92.762       ,173.73));
        cidades.add(new Cidade("Ponte Serrada"                   ,null      ,null,null));
        cidades.add(new Cidade("Pouso Redondo"                   ,null      ,null,null));
        cidades.add(new Cidade("Porto União"                     ,33497      ,851.239     ,39.3));
        cidades.add(new Cidade("Presidente Castello Branco"      ,null        ,70.211  ,null     ));
        cidades.add(new Cidade("Praia Grande"                    ,7270        ,278.576      ,26.1));
        cidades.add(new Cidade("Presidente Nereu"                ,null        ,null  ,null));
        cidades.add(new Cidade("Presidente Getúlio"              ,null        ,null  ,null));
        cidades.add(new Cidade("Quilombo"                        ,10201       ,279.200      ,36.53));
        cidades.add(new Cidade("Princesa"                        ,null  ,null,null));
        cidades.add(new Cidade("Rio das Antas"                   ,null      ,null,null));
        cidades.add(new Cidade("Rancho Queimado"                 ,2748        ,286.432      ,9.59));
        cidades.add(new Cidade("Rio do Oeste"                    ,null      ,null,null));
        cidades.add(new Cidade("Rio do Campo"                    ,null      ,null,null));
        cidades.add(new Cidade("Rio dos Cedros"                  ,null      ,null,null));
        cidades.add(new Cidade("Rio do Sul"                      ,71061       ,260.97       ,253.88));
        cidades.add(new Cidade("Rio Negrinho"                    ,41060       ,908.391      ,45.2));
        cidades.add(new Cidade("Rio Fortuna"                     ,null  ,null,null));
        cidades.add(new Cidade("Riqueza"                         ,null  ,null,null));
        cidades.add(new Cidade("Rio Rufino"                      ,null  ,null,null));
        cidades.add(new Cidade("Romelândia"                      ,null  ,null,null));
        cidades.add(new Cidade("Rodeio"                          ,null  ,null,null));
        cidades.add(new Cidade("Saltinho"                        ,null  ,null,null));
        cidades.add(new Cidade("Salete"                          ,null,210.000     ,null  ));
        cidades.add(new Cidade("Sangão"                          ,null  ,null,null));
        cidades.add(new Cidade("Salto Veloso"                    ,null      ,null,null));
        cidades.add(new Cidade("Santa Helena"                    ,null      ,null,null));
        cidades.add(new Cidade("Santa Cecília"                   ,null, 1145.810    ,null     ));
        cidades.add(new Cidade("Santa Rosa do Sul"               ,null        ,null  ,null));
        cidades.add(new Cidade("Santa Rosa de Lima"              ,null        ,null  ,null));
        cidades.add(new Cidade("Santa Terezinha do Progresso"    ,null        ,null             ,null ));
        cidades.add(new Cidade("Santa Terezinha"                 ,null      ,null,null));
        cidades.add(new Cidade("Santo Amaro da Imperatriz"       ,21910       ,344.049      ,63.68));
        cidades.add(new Cidade("Santiago do Sul"                 ,1260        ,73.562       ,18.88));
        cidades.add(new Cidade("São Bernardino"                  ,null      ,null,null));
        cidades.add(new Cidade("São Bento do Sul"                ,84507       ,495.578      ,150.93));
        cidades.add(new Cidade("São Carlos"                      ,null  ,null,null));
        cidades.add(new Cidade("São Bonifácio"                   ,null      ,null,null));
        cidades.add(new Cidade("São Domingos"                    ,null      ,null,null));
        cidades.add(new Cidade("São Cristóvão do Sul"            ,null        ,null      ,null));
        cidades.add(new Cidade("São João Batista"                ,26260       ,220.726      ,118.97));
        cidades.add(new Cidade("São Francisco do Sul"            ,42569       ,540.800      ,78.71));
        cidades.add(new Cidade("São João do Oeste"               ,null        ,null  ,null));
        cidades.add(new Cidade("São João do Itaperiú"            ,null        ,null      ,null));
        cidades.add(new Cidade("São Joaquim"                     ,26045       ,1885.608     ,13.81));
        cidades.add(new Cidade("São João do Sul"                 ,null      ,null,null));
        cidades.add(new Cidade("São José do Cedro"               ,null        ,null  ,null));
        cidades.add(new Cidade("São José"                        ,246586      ,152.387      ,1573.09));
        cidades.add(new Cidade("São Lourenço do Oeste"           ,24076       ,356.316      ,65.46));
        cidades.add(new Cidade("São José do Cerrito"             ,null        ,null  ,null));
        cidades.add(new Cidade("São Martinho"                    ,null      ,null,null));
        cidades.add(new Cidade("São Ludgero"                     ,10993       ,107.571      ,102.19));
        cidades.add(new Cidade("São Miguel do Oeste"             ,40482       ,234.396      ,168.05));
        cidades.add(new Cidade("São Miguel da Boa Vista"         ,null        ,null      ,null));
        cidades.add(new Cidade("Saudades"                        ,null  ,null,null));
        cidades.add(new Cidade("São Pedro de Alcântara"          ,5139        ,140.016      ,null));
        cidades.add(new Cidade("Seara"                           ,17541       ,null ,null));
        cidades.add(new Cidade("Schroeder"                       ,null  ,null,null));
        cidades.add(new Cidade("Siderópolis"                     ,null  ,null,null));
        cidades.add(new Cidade("Serra Alta"                      ,null  ,null,null));
        cidades.add(new Cidade("Sul Brasil"                      ,null  ,null,null));
        cidades.add(new Cidade("Sombrio"                         ,26626       ,142.745      ,186.53));
        cidades.add(new Cidade("Tangará"                         ,null  ,null,null));
        cidades.add(new Cidade("Taió"                            ,17265       ,693.025      ,24.91));
        cidades.add(new Cidade("Tijucas"                         ,36170       ,276.622      ,130.76));
        cidades.add(new Cidade("Tigrinhos"                       ,null  ,null,null));
        cidades.add(new Cidade("Timbó"                           ,42045       ,127251.0       ,330.01));
        cidades.add(new Cidade("Timbé do Sul"                    ,5379        ,330.079      ,16.3));
        cidades.add(new Cidade("Três Barras"                     ,null  ,null,null));
        cidades.add(new Cidade("Timbó Grande"                    ,9856        ,596.942      ,16.51));
        cidades.add(new Cidade("Treze de Maio"                   ,null      ,null,null));
        cidades.add(new Cidade("Treviso"                         ,null  ,null,null));
        cidades.add(new Cidade("Trombudo Central"                ,null        ,null  ,null));
        cidades.add(new Cidade("Treze Tílias"                    ,null      ,null,null));
        cidades.add(new Cidade("Tunápolis"                       ,null  ,null,null));
        cidades.add(new Cidade("Tubarão"                         ,105686      ,300.3        ,322.23));
        cidades.add(new Cidade("União do Oeste"                  ,null        ,null          ,null));
        cidades.add(new Cidade("Turvo"                           ,11854       ,233.941      ,50.67));
        cidades.add(new Cidade("Urupema"                         ,2472        ,350.037      ,7.06));
        cidades.add(new Cidade("Urubici"                         ,10702       ,1019.232     ,10.5));
        cidades.add(new Cidade("Vargeão"                         ,3573        ,null ,null));
        cidades.add(new Cidade("Urussanga"                       ,20223       ,240.476      ,84.1));
        cidades.add(new Cidade("Vargem Bonita"                   ,null      ,null,null));
        cidades.add(new Cidade("Vargem"                          ,null  ,null,null));
        cidades.add(new Cidade("Videira"                         ,53065       ,377.852      ,138.97));
        cidades.add(new Cidade("Vidal Ramos"                     ,null  ,null,null));
        cidades.add(new Cidade("Witmarsum"                       ,3556        ,150.798      ,20.0));
        cidades.add(new Cidade("Vitor Meireles"                  ,null      ,null,null));
        cidades.add(new Cidade("Xavantina"                       ,3933        ,215.069      ,18.6));
        cidades.add(new Cidade("Xanxerê"                         ,50982       ,381.41       ,109.5));
        cidades.add(new Cidade("Zortéa"                          ,2981        ,190.149      ,15.1));
        cidades.add(new Cidade("Xaxim"                           ,28706       ,294.715      ,85.3));
    }

    public List<Cidade> getCidades(String nameFilter) {
        List<Cidade> cidadesFiltered = new ArrayList<>();

        for (Cidade cidade : cidades) {
            if (cidade.getNome().toLowerCase().contains(nameFilter.toLowerCase())) {
                cidadesFiltered.add(cidade);
            }
        }

        return cidadesFiltered;
    }

    public List<Cidade> getCidades() {
        return cidades;
    }

}
